#define SYSTEM_G711_PAGE		(SYSTEM_DSP_PAGE + 0)
#define SYSTEM_G711_OFFSET		0x0
#define SYSTEM_GSM_PAGE		(SYSTEM_DSP_PAGE + 0)
#define SYSTEM_GSM_OFFSET		0x4144
#define SYSTEM_G729_PAGE		(SYSTEM_DSP_PAGE + 0)
#define SYSTEM_G729_OFFSET		0xb702
#define SYSTEM_ILBC_PAGE		(SYSTEM_DSP_PAGE + 1)
#define SYSTEM_ILBC_OFFSET		0x9fc8
#define SYSTEM_SPEEX_PAGE		(SYSTEM_DSP_PAGE + 2)
#define SYSTEM_SPEEX_OFFSET		0x6b2a
#define SYSTEM_SPX_TAB4K_PAGE		(SYSTEM_DSP_PAGE + 3)
#define SYSTEM_SPX_TAB4K_OFFSET		0x6bcc
#define SYSTEM_SPX_TAB6K_PAGE		(SYSTEM_DSP_PAGE + 3)
#define SYSTEM_SPX_TAB6K_OFFSET		0x738c
#define SYSTEM_SPX_TAB8K_PAGE		(SYSTEM_DSP_PAGE + 3)
#define SYSTEM_SPX_TAB8K_OFFSET		0x7bac
#define SYSTEM_SPX_TAB11K_PAGE		(SYSTEM_DSP_PAGE + 3)
#define SYSTEM_SPX_TAB11K_OFFSET		0x85ac
#define SYSTEM_SPX_TAB15K_PAGE		(SYSTEM_DSP_PAGE + 3)
#define SYSTEM_SPX_TAB15K_OFFSET		0x97ec
#define SYSTEM_SPX_TAB18K_PAGE		(SYSTEM_DSP_PAGE + 3)
#define SYSTEM_SPX_TAB18K_OFFSET		0xa1ec
#define SYSTEM_SPX_TAB25K_PAGE		(SYSTEM_DSP_PAGE + 3)
#define SYSTEM_SPX_TAB25K_OFFSET		0xb72c
