"DHCP ...",  
"DHCP Fallito",
"Logon OK",
"Logon Fallito",
"missed calls",
"PPPoE ...",
"Pronto",
"Modo TFTP",
"Modo HTTP",
"Modo Auto-prov",
"Voicemail: ",
"Componi num:",
"Inoltro ...",
"Tono di libero",
"Chi. in attesa",
"Connesso",
"Riagganciare",
"Ragione Scon.",
"Aut. in attesa",
"Numero vuoto",
"Numero errato",
"Occupato",
"No risposta",
"Chi. rigettata",
"Chi. conclusa",
"Timeout rich.",
"Problema codec",
"Ris. Limitate",
"Err ServerIP",
"Trasfer Fallito",
"Trasfer OK",
"Parcheggiata",
"Trasferimento",
"Ottieni Data...",
"Ottieni Imp ...",
"Ottieni Fw ...",
"Volume+",
"Volume-",
"Contatto ",
"Microf. silente",
"Non Disturbare",
"SNTP fallito",
"Deviazione",
"PPPoE Failed",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
