"DHCP ...",  
"DHCP Failed",
"Logon OK",
"Logon Failed",
"missed calls",
"PPPoE ...",
"Phone Ready",
"TFTP Mode",
"HTTP Mode",
"Auto-prov Mode",
"Voicemail: ",
"Enter Number:",
"Calling ...",
"Ringing ...",
"Call Waiting",
"Connected",
"Please Hangup",
"Unknown Reason",
"Not Logon yet",
"Empty Number",
"Wrong Number",
"Peer Busy",
"Peer No Answer",
"Peer Reject",
"Peer Hangup",
"Request Timeout",
"Coder Mismatch",
"Res Limited",
"Bad ServerIP",
"Transfer Failed",
"Transfer Done",
"Call On Hold",
"Transfer ...",
"Get Date&Time...",
"Get Settings ...",
"Get Firmware ...",
"Vol+",
"Vol-",
"Memory Dial ",
"Call Muted",
"Do Not Disturb",
"Can't Get Date",
"Call Forwarded",
"PPPoE Failed",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
