"DHCP ...",  
"DHCP loi",
"Da vao mang",
"Vao mang loi",
"Cac cuoc goi nho",
"PPPoE ...",
"San sang goi",
"Che do TFTP",
"Che do HTTP",
"Che do cau hinh tu dong ",
"Hom thu thoai: ",
"Vao so dien thoai:",
"Dang goi ...",
"Dang chuong ...",
"Dang cho cuoc goi",
"Da ket noi",
"Hay dat may",
"Khong ro li do",
"Chua vao mang",
"Khong co so",
"So bi sai",
"Dau day ben kia ban",
"Dau day ben kia khong tra loi",
"Dau day ben kia huy cuoc goi",
"Dau day ben kia da nhac may",
"Yeu cau da het han",
"Ma hoa thoai khong dung",
"Gioi han tai nguyen",
"Dia chi may chu khong tot",
"Truyen di loi",
"Truyen thanh cong",
"Dang giu cuoc goi",
"Dang truyen ...",
"Lay gio...",
"Dang cai dat ...",
"Dang tai phan mem ...",
"Tang am luong+",
"Giam am luong-",
"Bo nho so dien thoai",
"Ngat noi",
"Khong lam phien",
"Khong the lay ngay",
"Da chuyen cuoc goi",
"PPPoE loi",
"Cong 1 da duoc noi",
"Cong 1 da duoc ngat ra",
"Cong 2 da duoc noi",
"Cong 2 da duco ngat ra",
"[Trong]",
"PIN yeu",
"Dang dung PIN",
"Ban phim tot!",
"Man hinh LCD tot!",
"LED tot!",
