"DHCP ...",  
"DHCP Baþarýsýz",
"Logon OK",
"Logon Baþarýsýz",
"Cevapsýz Çaðr",
"PPPoE ...",
"Telefon Hazýr",
"TFTP Mod",
"HTTP Mod",
"Auto-prov Mod",
"Sesli Mesaj: ",
"Numara Giriniz:",
"Arýyor ...",
"Arayan",
"Arama Beklemede",
"Baðland",
"Lütfen Kapatýn",
"Sebep Bilinmiyor",
"Kayýt Baþarýsýz", 
"Numara Yok",
"Yanlýþ Numara",
"Meþgul",
"Cevapsýz",
"Reddetme",
"Kapama",
"Ýstek Baþarýsýz",
"Koder Uyumsuz",
"Res Limitli",
"Köt?SunucuIP",
"Trans. Baþarýsýz",
"Trans. Yapýld",
"Arama Beklemede",
"Transfer ...",
"Tarih&Saat ...",
"Ayarlar Alýnýyor",
"Firmware ...",
"Ses+",
"Ses-",
"Hafýzadan Arama",
"Arama Sessizde",
"Rahatsýz Edilmeme",
"Tarih Alýnamad",
"Arama Yönlendi",
"PPPoE Baþarýsýz",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
