"DHCP...",  
"DHCP falhou",
"Logon OK",
"Logon falhou",
"Chamadas perd.",
"PPPoE...",
"Tel. pronto",
"Modo TFTP",
"Modo HTTP",
"Modo Auto-prov.",
"Correio de voz:",
"Número:",
"Discando...",
"Chamando:",
"Chamada em esp.",
"Conectado",
"Desligue",
"Motivo desc.",
"Não logado",
"Número vazio",
"Núm. incorreto",
"Ocupado",
"Não atende",
"Rejeitado",
"Desconectado",
"Tempo esgotado",
"Codec incorreto",
"Recs. limitados",
"IP serv. err.",
"Transf. falhou",
"Transf. OK",
"Chamada em esp.",
"Transf...",
"Ob. data/hora..",
"Ob. configs..",
"Ob. firmware..",
"Vol+",
"Vol-",
"Memória ",
"Mudo",
"Não perturbe",
"Impos. ob. data",
"Chamada desv.",
"PPPoE falhou",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
