"DHCP ...",  
"DHCP Baþarýsýz",
"Logon OK",
"Logon Baþarýsýz",
"Cevapsýz Çaðrý",
"PPPoE ...",
"Telefon Hazýr",
"      TFTP Mod",
"      HTTP Mod",
"Auto-prov Mod",
"Sesli Mesaj: ",
"Numara Giriniz:",
"Arýyor ...",
"       Arayan",
"Arama Beklemede",
"Baðlandý",
"Lütfen Kapatýn",
"Sebep Bilinmiyor",
"Kayýt Baþarýsýz", 
"Numara Yok",
"Yanlýþ Numara",
"Meþgul",
"Cevapsýz",
"Reddetme",
"",
"Ýstek Baþarýsýz",
"Koder Uyumsuz",
"Res Limitli",
"Kötü SunucuIP",
"Trans. Baþarýsýz",
"Trans. Yapýldý",
"Arama Beklemede",
"Transfer ...",
"Tarih&Saat ...",
"Ayarlar Alýnýyor",
"Firmware ...",
"Ses+",
"Ses-",
"Hafýzadan Arama",
"Arama Sessizde",
"Rahatsýz Edilmeme",
"Tarih Alýnamadý",
"Arama Yönlendi",
"PPPoE Baþarýsýz",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
"Rehber          Menü",
"       KAREL        ",
"Sil              Ara",
"Detay           Menü",
"Sessiz        Reddet",
"               Kapat",
"Dinle      >    Menü",
"Dinle           Menü",
"Tüm Ledler Kýrmýzý",
"Yanýyor mu?",
"Evet           Hayýr",
"Ekrandaki Tüm",
"Karakterler Dolu ise",
"1e deðilse 0a basýn",
"         ileri",
"Alarm Zaman?",
"Park PBook Menu Flas",
"Trans Redial HFree",
"VolDown VolUp Mute",
"Alarm Aç\Kapat",
"Transfer Yapýldý",
"Lütfen Kapatýn",
"Alarm Kapalý",
"Alarm Açýk",
"00:00",
"Türkçe",
"IP20_v_AAT",
"Evet",
"Hayýr",

/*
"Park PBook Menu Flas",
"Trans Redial HFree",
"VolDown VolUp Mute",
*/
//"Geri    <  >     Seç",
