"DHCP ...",  
"DHCP a eºuat",
"Logarea reuºitã",
"Logarea a eºuat",
"missed calls",
"PPPoE ...",
"Telefon Pregãtit",
"Mod TFTP",
"Mod HTTP",
"Mod Auto-Config.",
"Mesaje Vocale:",
"Introd. Numãrul:",
"Apel în curs ...",
"Vã Apeleazã ...",
"Apel în aºtept.",
"Connectat",
"Pune-þi Recep.",
"Motiv Necunoscut",
"Not Logon yet",
"Lipsã Numãr",
"Numãr Incorect",
"Numãr Ocupat",
"Lipsã Rãspuns",
"Apel Respins",
"Apel Terminat",
"Request Timeout",
"Codec Necunoscut",
"Lipsã Resurse",
"ServerIP Incorect",
"Transfer eºuat",
"Transf. efectuat",
"Apel în Aºtept.",
"Transfer ...",
"Obþin. Data/Timp",
"Obþin. Setãrilor",
"Obþin. Firmware",
"Volum+",
"Volum-",
"Memory Dial ",
"Apel fãrã Volum",
"Nu Deranjaþi",
"Obþ Datei eºuat",
"Apel Deviat",
"PPPoE Failed",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
