"DHCP ...",  
"Error en DHCP",
"Registrado",
"No registrado",
"missed calls",
"PPPoE ...",
"Teléfono Listo",
"Modo TFTP",
"Modo HTTP",
"Modo Auto-prov",
"Voicemail: ",
"Marca el número",
"Llamando ...",
"Sonando ...",
"Call Waiting",
"Conectado",
"Por favor cuelga",
"Unknown Reason", 
"No registrado",
"Sin Número",
"Número erroneo",
"Ocupado",
"No contesta",
"Rechazada",
"Llam. Finalizada",
"Codec distinto",
"Coder Mismatch",
"Res Limitada",
"ServerIP erronea",
"Falló desvio",
"Transferencia OK",
"Llamada On Hold",
"Transfiriendo ...",
"Obt.Fecha...",
"Obt.Settings ...",
"Obt.Firmware ...",
"Vol+",
"Vol-",
"Discar memoria",
"Silenciado",
"No molestar",
"Sin Fecha y Hora",
"Llamada desviada",
"PPPoE Failed",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
