"Attente DHCP ...",  
"Echec DHCP !",
"Logon réussi",
"Echec logon !",
"missed calls",
"PPPoE ...",
"Prêt",
"Mode TFTP",
"Mode HTTP",
"Mode Auto-approv",
"Messagerie : ",
"Composez :",
"Appel ...",
"Attente réponse",
"Appel en attente",
"En communication",
"Raccrochez",
"Raison inconnue",
"Non connecté",
"Numéro vide",
"Mauvais numéro",
"Occupé",
"Pas de réponse",
"Appel rejeté",
"Fin de l'appel",
"Pas de réponse",
"Problème codec",
"Res. limitées",
"Erreur IP serv.",
"Echec transfert!",
"Transfert OK",
"Appel en attente",
"Transfert ...",
"MAJ date ...",
"MAJ config ...",
"MAJ logiciel ...",
"Volume +",
"Volume -",
"Contact ",
"Micro coupé",
"Ne pas déranger",
"Echec MAJ date !",
"App. transféré",
"PPPoE Failed",
"Port1 Linked",
"Port1 Un-plugged",
"Port2 Linked",
"Port2 Un-plugged",
"[Empty]",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
"Battery low",
"On battery",
"Key OK!",
"LCD OK!",
"LED OK!",
