#ifdef OEM_IP20
#define WEB_INFO_NUM	82
#elif defined OEM_INNOMEDIA
#define WEB_INFO_NUM	81
#elif defined OEM_BT2008
#define WEB_INFO_NUM	87
#elif defined OEM_ROIP
#define WEB_INFO_NUM	83
#else
#define WEB_INFO_NUM	82
#endif

const unsigned short web_info_code[WEB_INFO_NUM] = {
OPT_IP_TYPE, 
OPT_IP_ADDRESS, 
OPT_SUBNET_MASK, 
OPT_ROUTER_IP, 
OPT_PPPOE_ID, 
OPT_PPPOE_PIN, 
OPT_DNS_TYPE, 
OPT_DNS_IP, 
OPT_DNS_IP2, 
OPT_LAY3_QOS, 
OPT_VLAN_TAG, 
OPT_QOS_PRIORITY, 
OPT_VOICE_CODER0, 
OPT_FRAME_NUMBER0, 
OPT_VOICE_CODER1, 
OPT_FRAME_NUMBER1, 
OPT_VOICE_CODER2, 
OPT_FRAME_NUMBER2, 
OPT_VOICE_CODER3, 
OPT_FRAME_NUMBER3, 
OPT_VOICE_CODER4, 
OPT_FRAME_NUMBER4, 
OPT_VOICE_CODER5, 
OPT_FRAME_NUMBER5, 
OPT_VOICE_CODER6, 
OPT_FRAME_NUMBER6, 
OPT_ILBC_FRAME, 
OPT_SPEEX_RATE, 
OPT_VAD, 
OPT_AGC, 
OPT_AEC, 
OPT_REGISTER, 
OPT_SIP_PROXY, 
OPT_SIP_PORT, 
OPT_SIP_DOMAIN, 
OPT_OUTBOUND_PROXY, 
OPT_DNS_SRV, 
OPT_USER_NUMBER, 
OPT_AUTH_ID, 
OPT_AUTH_PIN, 
OPT_USER_NAME, 
OPT_LOCAL_PORT, 
OPT_RTP_PORT, 
OPT_REGISTER_TTL, 
OPT_KEEP_ALIVE, 
OPT_DTMF_TYPE, 
OPT_DTMF_PAYLOAD, 
OPT_ADPCM32_PAYLOAD, 
OPT_ILBC_PAYLOAD, 
OPT_SPEEX_PAYLOAD, 
OPT_MESSAGE_NUMBER, 
OPT_PRACK, 
OPT_SUBSCRIBE_MWI, 
OPT_PROXY_REQUIRE, 
OPT_NAT_TRAVERSAL, 
OPT_NAT_IP, 
OPT_STUN_SERVER, 
OPT_STUN_PORT, 
OPT_FWD_NUMBER, 
OPT_FWD_ALWAYS, 
OPT_FWD_BUSY, 
OPT_FWD_NOANSWER, 
OPT_NOANSWER_TIMEOUT, 
OPT_AUTO_ANSWER, 
OPT_CALL_WAITING, 
OPT_DIAL_PREFIX, 
OPT_HOTLINE_NUMBER, 
OPT_USE_DIGITMAP, 
OPT_DIGITMAP_TIMEOUT,	// 69
#ifndef OEM_IP20
OPT_POUND_AS_CALL, 
#endif
#ifdef OEM_BT2008
OPT_REDIAL_TIMEOUT, 
OPT_CALL_LOG_TIMEOUT, 
OPT_RINGING, 
OPT_GRADUAL_RINGING, 
OPT_GET_VOICE_MSG,
#endif
OPT_ADMIN_PIN, 
#ifdef OEM_INNOMEDIA
OPT_ADMIN_USER,
#endif
OPT_SYSLOG_IP, 
OPT_VOL_INPUT, 
OPT_VOL_OUTPUT, 
#ifdef OEM_IP20
OPT_TIME_OUT,
#endif
OPT_SPEAKER_VOL, 
OPT_RING_VOL_OUTPUT,
#ifndef OEM_INNOMEDIA
OPT_PROVISION_SERVER, 
OPT_PROVISION_PORT,
#endif 
OPT_PROVISION_TTL, 
OPT_SNTP_DNS, 
OPT_TIME_ZONE, 
OPT_DAY_LIGHT,
#ifdef OEM_ROIP
OPT_PTT_CONTROL
#endif
};
